version: '3.5'

services:

  postman-runner:
    build: .
    image: flaviostutz/postman-runner
    ports:
      - 2000:2000
    environment:
      - LOG_LEVEL=debug
      - RUN_ON_STARTUP=true
      - RUN_API_SERVER=false

